services:
  gateway:
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
    command: npm run  start:debug  --project api-gateway
    networks:
      - oms
    volumes:
      - ./:/app
  auth:
    build:
      context: .
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=oms
      - PORT=3001
    depends_on:
      - postgres
    command: npm run  start:debug  --project auth
    networks:
      - oms
    volumes:
      - ./:/app

  order:
    build:
      context: .
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=development
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=oms
      - PORT=3002
    depends_on:
      - postgres
    command: npm run  start:debug  --project order
    networks:
      - oms
    volumes:
      - ./:/app
  
  inventory:
    build:
      context: .
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=development
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=oms
      - PORT=3003
    depends_on:
      - postgres
    command: npm run  start:debug  --project inventory
    networks:
      - oms
    volumes:
      - ./:/app
    
  product:
    build:
      context: .
    ports:
      - "3004:3004"
    environment:
      - NODE_ENV=development
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=oms
      - PORT=3004
    depends_on:
      - postgres
    command: npm run  start:debug  --project product
    networks:
      - oms
    volumes:
      - ./:/app
  postgres:
    image: postgres:14-alpine
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: oms
    networks:
      - oms
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

networks:
  oms:
    driver: bridge