services:
  jenkins:
    image: jenkins/jenkins:lts-jdk11
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    networks:
      - oms
    volumes:
      - jenkins_data:/var/jenkins_home
    deploy:
      resources:
        limits:
          memory: 1G # Jenkins can be memory-heavy, 1G is a reasonable minimum.
          cpus: '0.5'
        reservations:
          memory: 512M
          cpus: '0.25'

volumes:
  jenkins_data:

networks:
  oms:
    driver: bridge
