services:
  postgres:
    image: postgres:14-alpine
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 3s
      retries: 5
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: oms
    networks:
      - oms-network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.1'
        reservations:
          memory: 128M
          cpus: '0.05'

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      # Basic Kafka Configuration
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LISTENERS: 'PLAINTEXT://:9092,CONTROLLER://:9093'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:9092'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:9093'
      KAFKA_BROKER_ID: 1
      KAFKA_NODE_ID: 1
      KAFKA_LOG_DIRS: '/tmp/kafka-logs'
      CLUSTER_ID: 'DK3WNslFRemFujcyCzKORw'
      
      # Replication and Topic Settings
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_DELETE_TOPIC_ENABLE: 'true'
      
      # Memory and JVM Optimizations
      KAFKA_HEAP_OPTS: '-Xmx1g -Xms1g'
      KAFKA_JVM_PERFORMANCE_OPTS: '-server -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:InitiatingHeapOccupancyPercent=35 -XX:+ExplicitGCInvokesConcurrent -XX:MaxInlineLevel=15'
      
      # Controller Timeout Settings (Increased to prevent overload)
      KAFKA_CONTROLLER_SOCKET_TIMEOUT_MS: 60000
      KAFKA_CONTROLLER_QUORUM_FETCH_TIMEOUT_MS: 60000
      KAFKA_CONTROLLER_QUORUM_ELECTION_TIMEOUT_MS: 30000
      KAFKA_CONTROLLER_QUORUM_ELECTION_BACKOFF_MAX_MS: 10000
      
      # Broker Heartbeat and Session Settings
      KAFKA_BROKER_SESSION_TIMEOUT_MS: 45000
      KAFKA_BROKER_HEARTBEAT_INTERVAL_MS: 15000
      KAFKA_CONTROLLER_QUORUM_REQUEST_TIMEOUT_MS: 60000
      
      # Log Settings for Better Performance
      KAFKA_LOG_FLUSH_INTERVAL_MESSAGES: 10000
      KAFKA_LOG_FLUSH_INTERVAL_MS: 1000
      KAFKA_LOG_RETENTION_HOURS: 24
      KAFKA_LOG_RETENTION_BYTES: 1073741824
      KAFKA_LOG_SEGMENT_BYTES: 1073741824
      KAFKA_LOG_SEGMENT_DELETE_DELAY_MS: 1000
      KAFKA_LOG_CLEANER_ENABLE: 'false'
      KAFKA_LOG_CLEANUP_POLICY: 'delete'
      KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS: 300000
      
      # Network and Socket Settings
      KAFKA_NUM_NETWORK_THREADS: 3
      KAFKA_NUM_IO_THREADS: 8
      KAFKA_SOCKET_SEND_BUFFER_BYTES: 102400
      KAFKA_SOCKET_RECEIVE_BUFFER_BYTES: 102400
      KAFKA_SOCKET_REQUEST_MAX_BYTES: 104857600
      
      # Disable unnecessary features
      KAFKA_AUTO_LEADER_REBALANCE_ENABLE: 'false'
      KAFKA_LEADER_IMBALANCE_CHECK_INTERVAL_SECONDS: 300
      KAFKA_LEADER_IMBALANCE_PER_BROKER_PERCENTAGE: 10
      
      # Controller Event Queue Settings
      KAFKA_CONTROLLER_QUORUM_EVENT_QUEUE_CAPACITY: 1000
      KAFKA_CONTROLLER_QUORUM_EVENT_QUEUE_TIMEOUT_MS: 30000
      
    networks:
      - oms-network
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics --bootstrap-server localhost:9092 --list || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '0.5'
        reservations:
          memory: 1G
          cpus: '0.25'

  redis:
    image: redis:7.2-alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - oms-network
    healthcheck:
      test: ["CMD", "redis-cli", "-h", "localhost", "-p", "6379", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

volumes:
  postgres_data:

networks:
  oms-network:
    driver: bridge
    external: true
