services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    image: jenkins-with-docker:latest
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    networks:
      - oms
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false -Xmx1g -Xms512m
    deploy:
      resources:
        limits:
          memory: 1G # Jenkins can be memory-heavy, 1G is a reasonable minimum.
          cpus: '0.5'
        reservations:
          memory: 512M
          cpus: '0.25'

volumes:
  jenkins_data:

networks:
  oms:
    driver: bridge
